const nav=document.querySelector('nav');
document.querySelector('.modal')?.remove();
document.querySelector('.cake-studio')?.remove();
document.querySelectorAll('.product-card').forEach(card=>card.style.background='#e6c8b3');
nav.querySelector('.nav-link')?.remove();
nav.insertAdjacentHTML('beforeend','<div class="nav-centre"><a href="about.html">About Us</a><span>·</span><a href="clients.html">Our Clients</a><span>·</span><a href="contact.html">Contact</a></div>');
const centre=document.querySelector('.nav-centre');
const homeMenuToggle=document.createElement('button');
homeMenuToggle.className='mobile-menu-toggle';
homeMenuToggle.type='button';
homeMenuToggle.setAttribute('aria-label','Open navigation menu');
homeMenuToggle.setAttribute('aria-expanded','false');
homeMenuToggle.textContent='☰';
nav.append(homeMenuToggle);
Object.assign(centre.style,{position:'absolute',left:'50%',top:'50%',transform:'translate(-50%,-50%)',display:'flex',gap:'13px',alignItems:'center',whiteSpace:'nowrap'});
centre.querySelectorAll('a').forEach(link=>Object.assign(link.style,{color:'#fff9ec',textDecoration:'none',font:'600 1rem Plus Jakarta Sans, sans-serif',letterSpacing:'.08em',textTransform:'uppercase'}));
homeMenuToggle.addEventListener('click',()=>{
  const isOpen=centre.classList.toggle('is-open');
  homeMenuToggle.setAttribute('aria-expanded',String(isOpen));
  homeMenuToggle.setAttribute('aria-label',isOpen?'Close navigation menu':'Open navigation menu');
  homeMenuToggle.textContent=isOpen?'×':'☰';
});
centre.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{
  centre.classList.remove('is-open');
  homeMenuToggle.setAttribute('aria-expanded','false');
  homeMenuToggle.setAttribute('aria-label','Open navigation menu');
  homeMenuToggle.textContent='☰';
}));
const renderHomeMenuToggle=isOpen=>{
  homeMenuToggle.innerHTML=isOpen?'&times;':'<span></span><span></span><span></span>';
};
renderHomeMenuToggle(false);
homeMenuToggle.addEventListener('click',()=>renderHomeMenuToggle(homeMenuToggle.getAttribute('aria-expanded')==='true'));
centre.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>renderHomeMenuToggle(false)));
document.querySelector('.hero-copy .eyebrow').textContent='YOUR COMPLETE PACKAGING PARTNER';
document.querySelector('.hero-copy h1').innerHTML='Everything your<br><em>business needs.</em>';
document.querySelector('.hero-text').textContent='A complete range of practical, presentable and versatile packaging solutions — made for the businesses behind every product.';
const sweetCard=document.querySelector('[data-product="sweet"]');
sweetCard.querySelector('.product-visual').innerHTML='<img src="assets/sweet-boxes.svg" alt="Plastic sweet boxes filled with Indian sweets">';
Object.assign(sweetCard.style,{gridColumn:'span 4',minHeight:'490px',borderRadius:'18px',overflow:'hidden',transition:'transform .35s ease, box-shadow .35s ease',cursor:'pointer'});
Object.assign(sweetCard.querySelector('.product-visual').style,{height:'300px',display:'grid',placeItems:'center',background:'transparent',overflow:'visible'});
Object.assign(sweetCard.querySelector('.product-visual img').style,{width:'100%',height:'100%',objectFit:'contain',padding:'0',transition:'transform .45s cubic-bezier(.2,.8,.2,1), filter .45s ease',transformOrigin:'center'});
sweetCard.querySelector('.card-copy button').remove();
Object.assign(sweetCard.querySelector('.card-copy').style,{display:'block',marginTop:'20px'});
Object.assign(sweetCard.querySelector('.number').style,{color:'#8f4935',fontWeight:'700',marginBottom:'10px'});
Object.assign(sweetCard.querySelector('h3').style,{fontWeight:'700',fontSize:'2rem',color:'#17251d',margin:'0'});
Object.assign(sweetCard.querySelector('.card-detail').style,{color:'#5f3d32',fontWeight:'600',marginTop:'12px'});
const sweetImage=sweetCard.querySelector('.product-visual img');
const animateSweet=active=>{sweetCard.style.transform=active?'translateY(-10px)':'translateY(0)';sweetCard.style.boxShadow=active?'0 22px 34px rgba(71,37,23,.22)':'none';sweetImage.style.transform=active?'scale(1.07) rotate(-1deg)':'scale(1) rotate(0deg)';sweetImage.style.filter=active?'drop-shadow(0 16px 14px rgba(80,39,18,.18))':'none'};
sweetCard.addEventListener('mouseenter',()=>animateSweet(true));
sweetCard.addEventListener('mouseleave',()=>animateSweet(false));
sweetCard.addEventListener('touchstart',()=>animateSweet(true),{passive:true});
sweetCard.addEventListener('touchend',()=>animateSweet(false),{passive:true});
sweetCard.addEventListener('click',()=>window.location.href='plastic-sweet-boxes.html');
const boardCard=document.querySelector('[data-product="board"]');
boardCard.querySelector('.product-visual').innerHTML='<img src="assets/itc-board.svg" alt="ITC board boxes">';
Object.assign(boardCard.style,{gridColumn:'span 4',minHeight:'490px',borderRadius:'18px',overflow:'hidden',transition:'transform .35s ease, box-shadow .35s ease',cursor:'pointer'});
Object.assign(boardCard.querySelector('.product-visual').style,{height:'300px',display:'grid',placeItems:'center',background:'transparent',overflow:'visible'});
const boardImage=boardCard.querySelector('.product-visual img');
Object.assign(boardImage.style,{width:'100%',height:'100%',objectFit:'contain',transition:'transform .45s cubic-bezier(.2,.8,.2,1), filter .45s ease',transformOrigin:'center'});
boardCard.querySelector('.card-copy button').remove();
Object.assign(boardCard.querySelector('.card-copy').style,{display:'block',marginTop:'20px'});
Object.assign(boardCard.querySelector('.number').style,{color:'#8f4935',fontWeight:'700',marginBottom:'10px'});
Object.assign(boardCard.querySelector('h3').style,{fontWeight:'700',fontSize:'2rem',color:'#17251d',margin:'0'});
Object.assign(boardCard.querySelector('.card-detail').style,{color:'#5f3d32',fontWeight:'600',marginTop:'12px'});
const animateBoard=active=>{boardCard.style.transform=active?'translateY(-10px)':'translateY(0)';boardCard.style.boxShadow=active?'0 22px 34px rgba(71,37,23,.22)':'none';boardImage.style.transform=active?'scale(1.07) rotate(1deg)':'scale(1) rotate(0deg)';boardImage.style.filter=active?'drop-shadow(0 16px 14px rgba(80,39,18,.18))':'none'};
boardCard.addEventListener('mouseenter',()=>animateBoard(true));boardCard.addEventListener('mouseleave',()=>animateBoard(false));boardCard.addEventListener('touchstart',()=>animateBoard(true),{passive:true});boardCard.addEventListener('touchend',()=>animateBoard(false),{passive:true});boardCard.addEventListener('click',()=>window.location.href='itc-board-boxes.html');
const containersCard=document.querySelector('[data-product="containers"]');
containersCard.querySelector('.card-detail').textContent='50ml to 1000ml Biryani Boxes';
containersCard.querySelector('.product-visual').innerHTML='<img src="assets/plastic-boxes.svg" alt="Clear plastic food containers">';
Object.assign(containersCard.style,{gridColumn:'span 4',minHeight:'490px',borderRadius:'18px',overflow:'hidden',transition:'transform .35s ease, box-shadow .35s ease',cursor:'pointer'});
Object.assign(containersCard.querySelector('.product-visual').style,{height:'300px',display:'grid',placeItems:'center',background:'transparent',overflow:'visible'});
const containersImage=containersCard.querySelector('.product-visual img');
Object.assign(containersImage.style,{width:'100%',height:'100%',objectFit:'contain',transition:'transform .45s cubic-bezier(.2,.8,.2,1), filter .45s ease',transformOrigin:'center'});
containersCard.querySelector('.card-copy button').remove();
Object.assign(containersCard.querySelector('.card-copy').style,{display:'block',marginTop:'20px'});
Object.assign(containersCard.querySelector('.number').style,{color:'#4e7169',fontWeight:'700',marginBottom:'10px'});
Object.assign(containersCard.querySelector('h3').style,{fontWeight:'700',fontSize:'2rem',color:'#17251d',margin:'0'});
Object.assign(containersCard.querySelector('.card-detail').style,{color:'#385750',fontWeight:'600',marginTop:'12px'});
const animateContainers=active=>{containersCard.style.transform=active?'translateY(-10px)':'translateY(0)';containersCard.style.boxShadow=active?'0 22px 34px rgba(34,74,66,.22)':'none';containersImage.style.transform=active?'scale(1.07) rotate(-1deg)':'scale(1) rotate(0deg)';containersImage.style.filter=active?'drop-shadow(0 16px 14px rgba(34,74,66,.18))':'none'};
containersCard.addEventListener('mouseenter',()=>animateContainers(true));containersCard.addEventListener('mouseleave',()=>animateContainers(false));containersCard.addEventListener('touchstart',()=>animateContainers(true),{passive:true});containersCard.addEventListener('touchend',()=>animateContainers(false),{passive:true});containersCard.addEventListener('click',()=>window.location.href='plastic-containers.html');
const corrugatedCard=document.querySelector('[data-product="corrugated"]');
corrugatedCard.querySelector('.product-visual').innerHTML='<img src="assets/corrugated-boxes.svg" alt="Corrugated shipping boxes">';
Object.assign(corrugatedCard.style,{gridColumn:'span 4',minHeight:'490px',borderRadius:'18px',overflow:'hidden',transition:'transform .35s ease, box-shadow .35s ease',cursor:'pointer'});
Object.assign(corrugatedCard.querySelector('.product-visual').style,{height:'300px',display:'grid',placeItems:'center',background:'transparent',overflow:'visible'});
const corrugatedImage=corrugatedCard.querySelector('.product-visual img');
Object.assign(corrugatedImage.style,{width:'100%',height:'100%',objectFit:'contain',transition:'transform .45s cubic-bezier(.2,.8,.2,1), filter .45s ease',transformOrigin:'center'});
corrugatedCard.querySelector('.card-copy button').remove();
Object.assign(corrugatedCard.querySelector('.card-copy').style,{display:'block',marginTop:'20px'});
Object.assign(corrugatedCard.querySelector('.number').style,{color:'#8f4935',fontWeight:'700',marginBottom:'10px'});
Object.assign(corrugatedCard.querySelector('h3').style,{fontWeight:'700',fontSize:'2rem',color:'#17251d',margin:'0'});
Object.assign(corrugatedCard.querySelector('.card-detail').style,{color:'#5f3d32',fontWeight:'600',marginTop:'12px'});
const animateCorrugated=active=>{corrugatedCard.style.transform=active?'translateY(-10px)':'translateY(0)';corrugatedCard.style.boxShadow=active?'0 22px 34px rgba(71,37,23,.22)':'none';corrugatedImage.style.transform=active?'scale(1.07) rotate(1deg)':'scale(1) rotate(0deg)';corrugatedImage.style.filter=active?'drop-shadow(0 16px 14px rgba(80,39,18,.18))':'none'};
corrugatedCard.addEventListener('mouseenter',()=>animateCorrugated(true));corrugatedCard.addEventListener('mouseleave',()=>animateCorrugated(false));corrugatedCard.addEventListener('touchstart',()=>animateCorrugated(true),{passive:true});corrugatedCard.addEventListener('touchend',()=>animateCorrugated(false),{passive:true});
corrugatedCard.addEventListener('click',()=>window.location.href='corrugated-boxes.html');
const cakeCard=document.querySelector('[data-product="cake"]');
cakeCard.querySelector('.product-visual').innerHTML='<img src="assets/cake-base.svg" alt="Gold and white cake bases">';
Object.assign(cakeCard.style,{gridColumn:'span 4',minHeight:'490px',borderRadius:'18px',overflow:'hidden',transition:'transform .35s ease, box-shadow .35s ease',cursor:'pointer'});
Object.assign(cakeCard.querySelector('.product-visual').style,{height:'300px',display:'grid',placeItems:'center',background:'transparent',overflow:'visible'});
const cakeImage=cakeCard.querySelector('.product-visual img');
Object.assign(cakeImage.style,{width:'100%',height:'100%',objectFit:'contain',transition:'transform .45s cubic-bezier(.2,.8,.2,1), filter .45s ease',transformOrigin:'center'});
cakeCard.querySelector('.card-copy button').remove();
Object.assign(cakeCard.querySelector('.card-copy').style,{display:'block',marginTop:'20px'});
Object.assign(cakeCard.querySelector('.number').style,{color:'#8f4935',fontWeight:'700',marginBottom:'10px'});
Object.assign(cakeCard.querySelector('h3').style,{fontWeight:'700',fontSize:'2rem',color:'#17251d',margin:'0'});
Object.assign(cakeCard.querySelector('.card-detail').style,{color:'#5f3d32',fontWeight:'600',marginTop:'12px'});
const animateCake=active=>{cakeCard.style.transform=active?'translateY(-10px)':'translateY(0)';cakeCard.style.boxShadow=active?'0 22px 34px rgba(71,37,23,.22)':'none';cakeImage.style.transform=active?'scale(1.07) rotate(-1deg)':'scale(1) rotate(0deg)';cakeImage.style.filter=active?'drop-shadow(0 16px 14px rgba(80,39,18,.18))':'none'};
cakeCard.addEventListener('mouseenter',()=>animateCake(true));cakeCard.addEventListener('mouseleave',()=>animateCake(false));cakeCard.addEventListener('touchstart',()=>animateCake(true),{passive:true});cakeCard.addEventListener('touchend',()=>animateCake(false),{passive:true});
cakeCard.addEventListener('click',()=>window.location.href='cake-bases.html');
const productCardLabels={sweet:'Plastic Sweet Boxes',board:'ITC Board Boxes',containers:'Plastic Containers',corrugated:'Corrugated Boxes',cake:'Cake Bases'};
document.querySelectorAll('.product-card').forEach(card=>{
  const productName=productCardLabels[card.dataset.product];
  card.insertAdjacentHTML('beforeend','<span class="card-open-indicator" aria-hidden="true">↗</span>');
  card.setAttribute('role','link');
  card.setAttribute('tabindex','0');
  card.setAttribute('aria-label',`Open ${productName}`);
  card.addEventListener('keydown',event=>{
    if(event.key==='Enter'||event.key===' '){event.preventDefault();card.click();}
  });
});
document.querySelectorAll('.explore-trigger').forEach(button=>button.addEventListener('click',()=>document.querySelector('#collection').scrollIntoView({behavior:'smooth'})));
